services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
      POSTGRES_HOST: db

  web:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    environment:
      DATABASE_URL: "postgres://postgres:password@db/app_db"
      RAILS_ENV: development

volumes:
  postgres_data: