services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_ex_db
      POSTGRES_HOST: db

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0

  sidekiq:
    image: realy-app:latest
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ".:/app"
    restart: always

volumes:
  postgres_data: