default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "password" %>
  host: <%= ENV["POSTGRES_HOST"] || "db" %>

development:
  <<: *default
  database: app_db

test:
  <<: *default
  database: app_db_test

production:
  <<: *default
  database: app_db