default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "password" %>
  host: <%= ENV["POSTGRES_HOST"] || "db" %>
  database: <%= ENV.fetch("POSTGRES_DB", "crypto_ex_db") %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "crypto_ex_test_db") %>

production:
  <<: *default
